# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=archive_context_87e26cea5a
ROOST_METHOD_SIG_HASH=archive_context_b08fd8d867


```
Scenario 1: Test successful extraction of archive file
Details:
  TestName: test_successful_extraction
  Description: This test verifies if the function successfully extracts the contents of a zipfile to a temporary directory.
Execution:
  Arrange: Create a zipfile with known contents. Store the current working directory.
  Act: Call the archive_context function with the zipfile as parameter.
  Assert: Check if the contents of the zipfile are successfully extracted in the temporary directory. The current working directory should be same as before.
Validation:
  This test is crucial as it verifies the primary functionality of the archive_context function. If the function fails to extract the zipfile, it is not meeting its basic requirement.

Scenario 2: Test successful handling of non-zipfile input
Details:
  TestName: test_non_zipfile_input
  Description: This test verifies if the function handles a non-zipfile input without crashing and gives an appropriate response.
Execution:
  Arrange: Create a non-zipfile input. Store the current working directory.
  Act: Call the archive_context function with the non-zipfile input as parameter.
  Assert: The function should not crash and should handle the invalid input gracefully. The current working directory should be same as before.
Validation:
  This test is important to ensure that the function is robust and able to handle invalid inputs without crashing the system.

Scenario 3: Test successful change of working directory
Details:
  TestName: test_change_working_directory
  Description: This test verifies if the function changes the current working directory to the extracted zipfile's directory and then reverts back to the original directory.
Execution:
  Arrange: Create a zipfile. Store the current working directory.
  Act: Call the archive_context function with the zipfile as parameter.
  Assert: The function should change the working directory to the extracted zipfile's directory during execution and should revert back to the original directory after execution. 
Validation:
  This test is important to ensure that the function does not disrupt the working environment by changing the current working directory permanently.

Scenario 4: Test successful cleanup after extraction
Details:
  TestName: test_cleanup_after_extraction
  Description: This test verifies if the function cleans up the temporary directory created for extraction after it finishes execution.
Execution:
  Arrange: Create a zipfile. 
  Act: Call the archive_context function with the zipfile as parameter.
  Assert: After the function finishes execution, the temporary directory created for extraction should not exist.
Validation:
  This test is important to ensure that the function does not leave behind any residual files or directories after execution, hence maintaining a clean working environment.
```
"""

# ********RoostGPT********
import os
import pytest
import shutil
import tempfile
import zipfile
from distutils import log
from ez_setup import archive_context, get_zip_class

class Test_EzSetupArchiveContext:

    @pytest.mark.regression
    def test_successful_extraction(self):
        # Arrange
        old_wd = os.getcwd()
        with tempfile.TemporaryDirectory() as tmpdir:
            zf = zipfile.ZipFile(os.path.join(tmpdir, 'test.zip'), 'w')
            zf.writestr('test.txt', 'Hello, World!')
            zf.close()

        # Act
        with archive_context(os.path.join(tmpdir, 'test.zip')):
            pass
            
        # Assert
        assert not os.path.exists(os.path.join(tmpdir, 'test.txt'))
        assert os.getcwd() == old_wd

    @pytest.mark.negative
    def test_non_zipfile_input(self):
        # Arrange
        old_wd = os.getcwd()
        with tempfile.NamedTemporaryFile() as tmpfile:
            tmpfile.write(b'Not a zip file')

        # Act
        with pytest.raises((zipfile.BadZipFile, zipfile.LargeZipFile)):
            with archive_context(tmpfile.name):
                pass

        # Assert
        assert os.getcwd() == old_wd

    @pytest.mark.regression
    def test_change_working_directory(self):
        # Arrange
        old_wd = os.getcwd()
        with tempfile.TemporaryDirectory() as tmpdir:
            zf = zipfile.ZipFile(os.path.join(tmpdir, 'test.zip'), 'w')
            zf.writestr('test.txt', 'Hello, World!')
            zf.close()

        # Act
        with archive_context(os.path.join(tmpdir, 'test.zip')) as ac:
            new_wd = os.getcwd()

        # Assert
        assert new_wd != old_wd
        assert os.getcwd() == old_wd

    @pytest.mark.regression
    def test_cleanup_after_extraction(self):
        # Arrange
        with tempfile.TemporaryDirectory() as tmpdir:
            zf = zipfile.ZipFile(os.path.join(tmpdir, 'test.zip'), 'w')
            zf.writestr('test.txt', 'Hello, World!')
            zf.close()

            # Act
            with archive_context(os.path.join(tmpdir, 'test.zip')):
                pass

            # Assert
            assert not os.path.exists(tmpdir)
