# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=get_best_downloader_aaacb7783c
ROOST_METHOD_SIG_HASH=get_best_downloader_6904ac27c3


Scenario 1: Validate that the function returns the first viable downloader
Details:
  TestName: test_first_viable_downloader_returned
  Description: This test is intended to verify that the function correctly returns the first viable downloader from the list of downloaders.
Execution:
  Arrange: Mock the downloaders in such a way that the first downloader is viable and the rest are not.
  Act: Call the get_best_downloader function.
  Assert: Check that the function returns the first downloader.
Validation:
  This test ensures that the function correctly prioritizes and returns the first viable downloader, as per the business logic.

Scenario 2: Validate that the function returns None when there are no viable downloaders
Details:
  TestName: test_no_viable_downloader
  Description: This test is intended to verify that the function returns None when none of the downloaders are viable.
Execution:
  Arrange: Mock the downloaders in such a way that none of them are viable.
  Act: Call the get_best_downloader function.
  Assert: Check that the function returns None.
Validation:
  This test verifies that the function handles the scenario where there are no viable downloaders, returning None as expected.

Scenario 3: Validate that the function returns the correct downloader when not all downloaders are viable
Details:
  TestName: test_some_viable_downloaders
  Description: This test is intended to verify that the function correctly returns a viable downloader when not all downloaders are viable.
Execution:
  Arrange: Mock the downloaders in such a way that only some of them are viable.
  Act: Call the get_best_downloader function.
  Assert: Check that the function returns one of the viable downloaders.
Validation:
  This test checks that the function correctly selects a viable downloader from a mixed list, ensuring that it doesn't incorrectly return a non-viable downloader.

Scenario 4: Validate that the function handles the scenario where all downloaders are viable
Details:
  TestName: test_all_viable_downloaders
  Description: This test is intended to verify that the function correctly returns the first downloader when all downloaders are viable.
Execution:
  Arrange: Mock the downloaders in such a way that all of them are viable.
  Act: Call the get_best_downloader function.
  Assert: Check that the function returns the first downloader.
Validation:
  This test ensures that the function correctly prioritizes the first downloader even when all downloaders are viable, adhering to the business logic.
"""

# ********RoostGPT********
import pytest
import ez_setup
from unittest.mock import MagicMock

# Test Class
class Test_EzSetupGetBestDownloader:

    @pytest.mark.positive
    def test_first_viable_downloader_returned(self):
        # Arrange
        first_downloader = MagicMock()
        first_downloader.viable = MagicMock(return_value=True)
        other_downloader = MagicMock()
        other_downloader.viable = MagicMock(return_value=False)
        ez_setup.downloaders = [first_downloader, other_downloader]

        # Act
        result = ez_setup.get_best_downloader()

        # Assert
        assert result == first_downloader

    @pytest.mark.negative
    def test_no_viable_downloader(self):
        # Arrange
        downloader = MagicMock()
        downloader.viable = MagicMock(return_value=False)
        ez_setup.downloaders = [downloader]

        # Act
        result = ez_setup.get_best_downloader()

        # Assert
        assert result is None

    @pytest.mark.positive
    def test_some_viable_downloaders(self):
        # Arrange
        viable_downloader = MagicMock()
        viable_downloader.viable = MagicMock(return_value=True)
        non_viable_downloader = MagicMock()
        non_viable_downloader.viable = MagicMock(return_value=False)
        ez_setup.downloaders = [non_viable_downloader, viable_downloader]

        # Act
        result = ez_setup.get_best_downloader()

        # Assert
        assert result == viable_downloader

    @pytest.mark.positive
    def test_all_viable_downloaders(self):
        # Arrange
        first_downloader = MagicMock()
        first_downloader.viable = MagicMock(return_value=True)
        other_downloader = MagicMock()
        other_downloader.viable = MagicMock(return_value=True)
        ez_setup.downloaders = [first_downloader, other_downloader]

        # Act
        result = ez_setup.get_best_downloader()

        # Assert
        assert result == first_downloader
