# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest6 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=has_powershell_adb85f6ea0
ROOST_METHOD_SIG_HASH=has_powershell_89e6f4a698


Scenario 1: Test With Non-Windows Platform
Details:
  TestName: test_has_powershell_non_windows
  Description: This test is designed to ensure that has_powershell returns False if the platform is not Windows.
Execution:
  Arrange: Mock the platform.system() function to return a non-Windows platform (e.g., "Linux").
  Act: Invoke the function has_powershell without any parameters.
  Assert: Check if the function has returned False.
Validation:
  This test validates that the function correctly identifies non-Windows platforms and returns False, as the PowerShell is not available on these platforms.

Scenario 2: Test With Windows Platform But Without PowerShell
Details:
  TestName: test_has_powershell_windows_without_powershell
  Description: This test verifies that the function returns False if the platform is Windows, but PowerShell is not available.
Execution:
  Arrange: Mock the platform.system() function to return "Windows". Also, Arrange the subprocess.check_call to raise an exception.
  Act: Invoke the function has_powershell without any parameters.
  Assert: Check if the function has returned False.
Validation:
  This test validates that the function correctly identifies the absence of PowerShell on a Windows platform and returns False.

Scenario 3: Test With Windows Platform With PowerShell
Details:
  TestName: test_has_powershell_windows_with_powershell
  Description: This test verifies that the function returns True if the platform is Windows, and PowerShell is available.
Execution:
  Arrange: Mock the platform.system() function to return "Windows". Also, Arrange the subprocess.check_call not to raise any exception.
  Act: Invoke the function has_powershell without any parameters.
  Assert: Check if the function has returned True.
Validation:
  This test validates that the function correctly identifies the presence of PowerShell on a Windows platform and returns True.

Scenario 4: Test That Devnull Is Closed
Details:
  TestName: test_devnull_closed
  Description: This test verifies that the devnull file is closed after the function execution, regardless of the result.
Execution:
  Arrange: Mock the open function to return a mock file object. Also, mock the platform.system and subprocess.check_call as needed.
  Act: Invoke the function has_powershell without any parameters.
  Assert: Check if the close method on the mock file object has been called.
Validation:
  This test validates that the function correctly manages resources and closes the devnull file, fulfilling good programming practices and avoiding potential leaks.
"""

# ********RoostGPT********
import os
import subprocess
import platform
import pytest
from unittest.mock import Mock, patch
from ez_setup import has_powershell

class Test_EzSetupHasPowershell:
    @pytest.mark.smoke
    @patch('platform.system')
    def test_has_powershell_non_windows(self, mock_system):
        mock_system.return_value = 'Linux'
        assert not has_powershell()

    @pytest.mark.regression
    @patch('subprocess.check_call')
    @patch('platform.system')
    def test_has_powershell_windows_without_powershell(self, mock_system, mock_check_call):
        mock_system.return_value = 'Windows'
        mock_check_call.side_effect = Exception('PowerShell not found')
        assert not has_powershell()

    @pytest.mark.regression
    @patch('subprocess.check_call')
    @patch('platform.system')
    def test_has_powershell_windows_with_powershell(self, mock_system, mock_check_call):
        mock_system.return_value = 'Windows'
        mock_check_call.return_value = 0
        assert has_powershell()

    @pytest.mark.regression
    @patch('builtins.open')
    @patch('platform.system')
    @patch('subprocess.check_call')
    def test_devnull_closed(self, mock_check_call, mock_system, mock_open):
        mock_file = Mock()
        mock_open.return_value = mock_file
        mock_system.return_value = 'Windows'
        mock_check_call.return_value = 0
        has_powershell()
        mock_file.close.assert_called_once()
