# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=has_powershell_adb85f6ea0
ROOST_METHOD_SIG_HASH=has_powershell_89e6f4a698


```
Scenario 1: Validate function on Non-Windows OS
Details:
  TestName: test_has_powershell_on_non_windows_os
  Description: This test verifies if the function correctly identifies non-windows operating systems and returns False accordingly.
Execution:
  Arrange: Set platform.system() to always return a non-Windows OS type like 'Linux'.
  Act: Invoke the has_powershell() function.
  Assert: Confirm that the result is False and powershell command is not attempted to be called.
Validation:
  Ensuring that the function correctly identifies non-Windows OS systems is crucial because the powershell command is unique to Windows OS, and calling it on non-Windows systems could lead to exceptions or errors.

Scenario 2: Validate function on Windows OS without powershell
Details:
  TestName: test_has_powershell_on_windows_without_ps
  Description: This scenario tests if the function correctly identifies absence of powershell and returns False accordingly on Windows systems.
Execution:
  Arrange: Define platform.system() to return 'Windows' and subprocess.check_call to throw an exception when powershell command is called.
  Act: Invoke the has_powershell() function.
  Assert: Confirm that the result is False.
Validation:
  Ensuring the function successfully identifies the lack of powershell on a Windows OS system and returns False, even when an exception is thrown, confirms that the function handles these errors and exceptions accurately.

Scenario 3: Validate function on Windows OS with powershell
Details:
  TestName: test_has_powershell_on_windows_with_ps
  Description: This scenario validates if the function correctly identifies presence of powershell and returns True accordingly on Windows systems.
Execution:
  Arrange: Define platform.system() to return 'Windows' and subprocess.check_call to not throw an exception when powershell command is called.
  Act: Invoke the has_powershell() function.
  Assert: Confirm that the result is True.
Validation:
  Verifying that the function correctly identifies the presence of powershell on a Windows OS system and subsequently returns True, confirms thorough testing of multiple common environments and scenarios.
```
Note: Arrange sections in the scenarios might require mocking of the platform.system() and subprocess.check_call functions. Also, these scenarios are based on the premise that Windows OS is the only system that supports powershell.
"""

# ********RoostGPT********
import os
import shutil
import sys
import tempfile
import zipfile
import optparse
import subprocess
import platform
import textwrap
import contextlib
import setuptools
import pkg_resources
from urllib.request import urlopen
from distutils import log
from site import USER_SITE
from ez_setup import has_powershell
import pytest
import mock

class Test_EzSetupHasPowershell:
    @pytest.mark.regression
    def test_has_powershell_on_non_windows_os(self):
        with mock.patch.object(platform, 'system', return_value='Linux'):
            assert has_powershell() == False

    @pytest.mark.regression
    def test_has_powershell_on_windows_without_ps(self):
        with mock.patch.object(platform, 'system', return_value='Windows'):
            with mock.patch.object(subprocess, 'check_call', side_effect=Exception):
                assert has_powershell() == False

    @pytest.mark.regression
    def test_has_powershell_on_windows_with_ps(self):
        with mock.patch.object(platform, 'system', return_value='Windows'):
            cmd = ['powershell', '-Command', 'echo test']
            with mock.patch.object(subprocess, 'check_call', return_value=0):
                assert has_powershell() == True
