# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=file_properties_templates_add_for_user_44411867f7
ROOST_METHOD_SIG_HASH=file_properties_templates_add_for_user_0da15df59d


```
Scenario 1: Successfully adding a file property template for a user
Details:
    TestName: test_add_valid_template_for_user
    Description: This test verifies that the file_properties_templates_add_for_user function successfully adds templates for given valid inputs.
Execution:
    Arrange: Initialize a mock user and a valid set of template details (name, description, fields).
    Act: Invoke file_properties_templates_add_for_user using the mock user and the valid template details.
    Assert: Ensure that the function returns an AddTemplateResult object.
Validation:
    The successful execution of the function with valid inputs and subsequent return of AddTemplateResult directly correlate to the function's specification and indicate successful implementation of the business requirement.

Scenario 2: Attempt to add duplicate template for a user
Details:
    TestName: test_add_duplicate_template_for_user
    Description: This test verifies that the file_properties_templates_add_for_user function prevents the addition of duplicate templates.
Execution:
    Arrange: Initialize a mock user and add a template. Then, prepare an attempt to add a template with the same details.
    Act: Invoke file_properties_templates_add_for_user twice with the same template details.
    Assert: Ensure that the function throws a ModifyTemplateError on the second invocation.
Validation:
    This test is important because it confirms the function's error handling, ensuring it preserves data integrity by preventing the addition of duplicate file property templates.

Scenario 3: Adding a template with invalid field values
Details:
    TestName: test_add_template_with_invalid_fields_for_user
    Description: This test verifies if invalid field values are not allowed by the file_properties_templates_add_for_user function.
Execution:
    Arrange: Initialize a mock user and a set of invalid template details (invalid fields value).
    Act: Invoke file_properties_templates_add_for_user function with the invalid field values.
    Assert: Ensure that the function throws a respective error or any kind of exception indicating invalid field value.
Validation:
    This highlights the function's ability to handle invalid field values without making abnormal operation or other unexpected behavior.

Scenario 4: Attempt to add a template with an invalid user
Details:
    TestName: test_add_template_with_invalid_user
    Description: This test verifies the method's response to a non-existent or invalid user.
Execution:
    Arrange: Initialize an invalid/mock non-existent user and valid template details (name, description, fields).
    Act: Invoke file_properties_templates_add_for_user function with the invalid user.
    Assert: Ensure that the function throws a respective error or any kind of exception indicating that the user does not exist.
Validation:
    This test verifies the function's ability to handle invalid user input appropriately and its robustness in ensuring that only valid users can add templates.

Scenario 5: Attempt to add a Template on behalf of a team member or admin
Details:
    TestName: test_add_template_on_behalf_of_admin_or_team
    Description: This test validates the function's restriction as mentioned in its description which states “This endpoint can't be called on a team member or admin's behalf.”
Execution:
    Arrange: Initialize a mock admin or team member user and some valid template details.
    Act: Invoke file_properties_templates_add_for_user function on behalf of the admin or team member.
    Assert: Ensure that the function throws ApiError.
Validation:
    This test ensures that the business rules mentioned in the function's description – prohibiting the operation on behalf of an admin or a team member – are correctly enforced.
```
"""

# ********RoostGPT********
import pytest
from unittest.mock import MagicMock, patch
from base import DropboxBase
from dropbox.file_properties import AddTemplateArg, AddTemplateResult

class Test_DropboxBaseFilePropertiesTemplatesAddForUser:

    @pytest.fixture
    def setup(self):
        self.base = DropboxBase()
        self.valid_name = "valid_name"
        self.valid_desc = "valid_desc"
        self.valid_fields = ["field1", "field2"]
        self.valid_user = "valid_user"
        self.invalid_user = "invalid_user"
        self.duplicate_name = "duplicate_name"
        self.invalid_fields = [1234, None, ""]
        self.admin_user = "admin_user"
    
    # Scenario 1: Successfully adding a file property template for a user
    def test_add_valid_template_for_user(self, setup):
        self.base.request = MagicMock(return_value=AddTemplateResult('id1'))
        result = self.base.file_properties_templates_add_for_user(self.valid_name, self.valid_desc, self.valid_fields)
        assert isinstance(result, AddTemplateResult)

    # Scenario 2: Attempt to add duplicate template for a user
    def test_add_duplicate_template_for_user(self, setup):
        self.base.request = MagicMock(side_effect=["id1", ValueError("Template already exists")])
        self.base.file_properties_templates_add_for_user(self.duplicate_name, self.valid_desc, self.valid_fields)
        with pytest.raises(ValueError):
            self.base.file_properties_templates_add_for_user(self.duplicate_name, self.valid_desc, self.valid_fields)
    
    # Scenario 3: Adding a template with invalid field values
    def test_add_template_with_invalid_fields_for_user(self, setup):
        with pytest.raises(ValueError):
            self.base.file_properties_templates_add_for_user(self.valid_name, self.valid_desc, self.invalid_fields)

    # Scenario 4: Attempt to add a template with an invalid user
    @patch('DropboxBase.DropboxBase.file_properties_templates_add_for_user', return_value='id1')
    def test_add_template_with_invalid_user(self, setup, mock_request):
        with pytest.raises(ValueError):
            self.base.file_properties_templates_add_for_user(self.valid_name, self.valid_desc, self.valid_fields)

    # Scenario 5: Attempt to add a Template on behalf of a team member or admin
    def test_add_template_on_behalf_of_admin_or_team(self, setup):
        with pytest.raises(ValueError):
            self.base.file_properties_templates_add_for_user(self.valid_name, self.valid_desc, self.valid_fields)
