# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=as_admin_ecada0b846
ROOST_METHOD_SIG_HASH=as_admin_57317d616e


Scenario 1: Validate handling of invalid admin ID
Details:
  TestName: test_as_admin_invalid_team_member_id
  Description: Test validates that function throws an exception when supplied with non-string type team_member_id.
Execution:
  Arrange: Instantiate a Dropbox object
  Act: Call the 'as_admin' function with an integer instead of a string for the 'team_member_id' parameter.
  Assert: Exception (TypeError) is raised.
Validation:
  The function expects a string type 'team_member_id', hence it is important to validate the correct exception behaviour for bad input.

Scenario 2: Test the creation of Dropbox object with admin ID
Details:
  TestName: test_as_admin_team_member_id
  Description: The test validates the correct creation of the Dropbox object using correct 'team_member_id' which should allow API calls on behalf of the 'admin' user.
Execution:
  Arrange: Create a Dropbox object instance.
  Act: Call the 'as_admin' function with a valid 'team_member_id' string.
  Assert: The created 'Dropbox' object has valid 'SELECT_ADMIN_HEADER' and valid 'team_member_id'.
Validation:
  Ensuring that the function can correctly accept a 'team_member_id' and create a valid 'Dropbox' object is crucial for the function to operate as intended and by business specifications.

Scenario 3: Test when passed None as 'team_member_id'
Details:
  TestName: test_as_admin_with_none_team_member_id
  Description: The test is to verify when None is passed as 'team_member_id', function should throw an exception.
Execution:
  Arrange: Create a new Dropbox object instance.
  Act: Call 'as_admin' function with None as 'team_member_id'.
  Assert: An appropriate exception (TypeError) should be raised.
Validation:
  The 'as_admin' method expects a 'team_member_id' with value. Hence, passing None for 'team_member_id' is an invalid operation and should result in exception. Verifying this behavior is a part of assessing the function against its specifications. 

Scenario 4: Test with empty string as 'team_member_id'
Details:
  TestName: test_as_admin_empty_team_member_id
  Description: The test would verify if the function throws an exception when an empty string is passed as 'team_member_id'. 
Execution:
  Arrange: Instantiate a new Dropbox object.
  Act: Call 'as_admin' function with an empty string for 'team_member_id'.
  Assert: The function should throw an exception (ValueError).
Validation:
  The test helps confirm function's behavior in line with specifications when invalid inputs are passed. An empty 'team_member_id' is invalid since it must be a valid admin's ID.  

Scenario 5: Determine if _get_dropbox_client_with_select_header runs with right args
Details:
  TestName: test_as_admin_calls_get_client_correctly
  Description: The test should ascertain if the 'as_admin' function correctly calls the '_get_dropbox_client_with_select_header' function with the correct arguments.
Execution:
  Arrange: Create a new Dropbox object instance and a mock '_get_dropbox_client_with_select_header' function.
  Act: Call 'as_admin' with a valid 'team_member_id' and check the call to '_get_dropbox_client_with_select_header'.
  Assert: '_get_dropbox_client_with_select_header' was called with arguments 'SELECT_ADMIN_HEADER' and 'team_member_id'.
Validation:
  Verifying this behavior is essential, as the results of 'as_admin' depend on the inputs to '_get_dropbox_client_with_select_header'. This will ensure 'as_admin' is functioning in line with the desired functionality and implementation.
"""

# ********RoostGPT********
import pytest
from dropbox.base_team import DropboxTeamBase
from dropbox_client import SELECT_ADMIN_HEADER

class Test_DropboxTeamAsAdmin:

    @pytest.mark.negative
    def test_as_admin_invalid_team_member_id(self):
        team = DropboxTeamBase(None)
        with pytest.raises(TypeError):
            dropbox_client = team.as_admin(12345)

    @pytest.mark.positive
    def test_as_admin_team_member_id(self):
        team = DropboxTeamBase(None)
        dropbox_client = team.as_admin('team_member_id_123')
        assert dropbox_client._headers[SELECT_ADMIN_HEADER] == 'team_member_id_123'

    @pytest.mark.negative
    def test_as_admin_with_none_team_member_id(self):
        team = DropboxTeamBase(None)
        with pytest.raises(TypeError):
            dropbox_client = team.as_admin(None)

    @pytest.mark.negative
    def test_as_admin_empty_team_member_id(self):
        team = DropboxTeamBase(None)
        with pytest.raises(ValueError):
            dropbox_client = team.as_admin('')

    @pytest.mark.positive
    def test_as_admin_calls_get_client_correctly(self, mocker):
        get_client = mocker.patch('dropbox.dropbox_client.DropboxTeamBase._get_dropbox_client_with_select_header')
        team = DropboxTeamBase(None)
        team.as_admin('team_member_id_pull')
        get_client.assert_called_once_with(SELECT_ADMIN_HEADER, 'team_member_id_pull')
