# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest6 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___5a2a9cb0e0
ROOST_METHOD_SIG_HASH=__init___681f374c35


```
Scenario 1: Check proper initialization of the PathRootError object.
Details:
  TestName: test_init_PathRootError_obj
  Description: This test ensures the successful initialization of the PathRootError object with given parameters and preventing modification of status_code and body which should always be 422, None respectively.
Execution:
  Arrange: Initialize request_id and error, both with custom test strings.
  Act: Create a new instance of PathRootError passing in the request_id and error.
  Assert: Check that the correct values were assigned to the request_id and error attributes of the PathRootError instance and the status_code and body are set to 422 and None respectively.
Validation:
  This test ensures that initialized attributes of the PathRootError object align with the input provided and status_code and body are assigned values fixed in the constructor.

Scenario 2: Check integrity of PathRootError object after initialization.
Details:
  TestName: test_PathRootError_obj_integrity
  Description: This test ensures the initial state of the object and prevents unwanted modification to the status_code and body after the object creation.
Execution:
  Arrange: Initialize a PathRootError object with custom parameters.
  Act: Try to modify the status_code and body attributes of the PathRootError instance.
  Assert: Check whether the status_code and body are unchanged and still 422 and None respectively.
Validation:
  This test is crucial to ensure the immutability of certain properties post-initialization maintaining the integrity of the object, guarding against potential errors caused by unwanted attribute changes.

Scenario 3: Confirm the error assignment in PathRootError.
Details:
  TestName: test_PathRootError_error_assignment
  Description: This test is designed to verify if the error parameter is properly assigned during the initialization.
Execution:
  Arrange: Initialize request_id with custom test string and set error as None.
  Act: Create a new instance of PathRootError passing in the request_id and None error.
  Assert: Check that error attribute of the PathRootError instance is None.
Validation:
  The success of this test means that the function correctly handles 'None' input, a fundamental requirement given the error parameter's optional nature.
```
"""

# ********RoostGPT********
import pytest
from exceptions import PathRootError

class Test_PathRootErrorInit:

    @pytest.mark.regression
    @pytest.mark.positive
    def test_init_PathRootError_obj(self):
        # Arrange
        request_id = 'TestID'
        error = 'TestError'
        expected_status_code = 422
        expected_body = None
        # Act
        path_root_error = PathRootError(request_id, error)
        # Assert
        assert path_root_error.request_id == request_id
        assert path_root_error.error == error
        assert path_root_error.status_code == expected_status_code
        assert path_root_error.body == expected_body

    @pytest.mark.regression
    @pytest.mark.negative
    def test_PathRootError_obj_integrity(self):
        # Arrange
        request_id = 'TestID'
        error = 'TestError'
        path_root_error = PathRootError(request_id, error)
        new_status_code = 500
        new_body = 'NewBody'
        # Try to change values
        path_root_error.status_code = new_status_code
        path_root_error.body = new_body
        # Assert
        assert path_root_error.status_code != new_status_code
        assert path_root_error.body != new_body

    @pytest.mark.regression
    @pytest.mark.negative
    def test_PathRootError_error_assignment(self):
        # Arrange
        request_id = 'TestID'
        error = None
        # Act
        path_root_error = PathRootError(request_id, error)
        # Assert
        assert path_root_error.error == error
